### ISSUE TITLE
[Suggestion] Prices set by the land sellers.

### ISSUE THREAD

**Issue by SrBedrock** [RoboMWM/GPRealEstate#1]
Add a way for the player to set a price for the land.

**Comment by RoboMWM** [comment]
Thanks for the suggestion! Apparently I didn't have a readme for this repo, so I went ahead and updated the readme regarding support for feature requests.

**Comment by SrBedrock** [comment]
Thanks!

**Comment by RoboMWM** [comment]
No need to close this issue, you can leave it here open even if you don't want to be a patron, in case someone else wants the idea implemented in the future. I use labels to schedule work.

**Comment by SrBedrock** [comment]
It's not that I don't want to be patreon.
It's just that I really can't afford it, thanks for your plugins <3

**Comment by RoboMWM** [comment]
In the meantime, you may be interested in [GPAuctions](https://github.com/robomwm/GPAuctions)

**Comment by NullCase** [comment]
players can set a price for the land. top line is [re] second line is price.

**Comment by NullCase** [comment]
This is the present functionality of GPR. Player specified prices go on line 2 when creating a real estate sign.
