### ISSUE TITLE
New sign types can create Real Estate sales but claim cannot be purchased using new signs.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPRealEstate#2]
Test: 
- create RealEstate sale using new sign type.
- have a player attempt to buy the claim.

![2019-08-07_17 25 44](https://user-images.githubusercontent.com/32785664/62659073-65e00c80-b938-11e9-8cc1-1321b36716d8.png)

Result:
- claim not purchased.
- holding shift + click does not display Real Estate information.
- basically clicking the sign does nothing.

Expected:
- Claim purchasable, shift+click displays RealEstate Info.

Also tested: I confirmed that using oak_sign still functions properly.

**Comment by RoboMWM** [comment]
Reason why this is happening is because the API compatibility layer is only translating SIGN -> OAK_SIGN and not accounting for any others.

**Comment by RoboMWM** [comment]
Will be converting project to `api-version: 1.15` to fix.

**Comment by NullCase** [comment]
OK, it sounds like both issues are (very likely) related to the api changes.

It's quite late here. I'll return tomorrow to check it out.

**Comment by NullCase** [comment]
oh, in case when I check tomorrow, do you have a link where I can dl the .jar?

Because i don't know how to compile them. Again, really late here. sorry for the short response.

**Comment by RoboMWM** [comment]
I put a link in the releases.

**Comment by NullCase** [comment]
Hi Robo. In that case, do you have a link to the releases?

**Comment by NullCase** [comment]
testing it now.

**Comment by NullCase** [comment]
OK great, it looks like that was a good one to fix. @RoboMWM great work. $ sent.

I don't know how to code, so sometimes tasks will be harder or easier. On balance I hope it works out great.

Is this a bad week to do some more Dev work? Because there are two player requests for GPR features. Both of them seem attainable, because its similar to our Auctions work: 
- A broadcast when offering Real Estate.
- Mail to the seller when a Real Estate offer is purchased.

Format would match Auctions which has both the broadcast and mail.

It looks like I can do another $30 for it. Let me know what you think and I'll write up two issues with specs.

**Comment by RoboMWM** [comment]
Both are doable, go ahead and writeup the issues. 

If you're looking for a template, the feature request one used for GP is a good start.
