### ISSUE TITLE
From zychohawk on the spigot thread, issues to investigate

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPRealEstate#4]
Hi @RoboMWM I'm just going to investigate these some time next year, when I have some money squired away for dev work. Listed here as a reminder for me. Happy New Year.

1. ~~If you break the block the sign is attached to, you get the dropped block but it shows back up due to the sign protection keeping it in place, essentially duplicating the connecting block.~~ [tested, no]
2. ~~If a claim has trustees, they are not removed upon he sale of the claim.~~ [tested, no]
3. at times, the claim sale reverts back to the original claim owner. [unable to replicate.]

https://www.spigotmc.org/threads/gp-realestate.87904/page-2

**Comment by RoboMWM** [comment]
Merry Christmas!

> 3.at times, the claim sale reverts back to the original claim owner.

That's strange.

**Comment by NullCase** [comment]
Untested issues still. However, if the claims being sold were actually subclaims then 2 and 3 above would be possible and intended (if unexpected).

**Comment by NullCase** [comment]
Was able to refute two of these. Still it seems like someone was tricked using subclaim sales.
