### ISSUE TITLE
Sign Fix Update [for pay]

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPRealEstate#5]
Hi @RoboMWM 

Is now a bad time for development work?

It looks like I have about $30 squirreled away to fix GPRealEstate signs. My goal would be to fund and test an update that fixes:

- signs placed on surfaces. https://github.com/RoboMWM/GPRealEstate/issues/3
- all new sign types. https://github.com/RoboMWM/GPRealEstate/issues/2

Presently those signs can be used to create Real Estate signs, but nobody can use them to buy the property. Right now only Oak signs placed 'standing' on the ground will function.

**Comment by RoboMWM** [comment]
k. Probably best to keep further discussion contained in those two issues.
