### ISSUE TITLE
broadcast Real Estate offer when created.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPRealEstate#6]
**As** a server OP
**I want** GPR to broadcast offers when created
**Because** this will indicate the location and price to help advertise what people are selling.

This is intended to mirror GPAuctions' broadcast.

/broadcast &f[&6RealEstate&f] &bA real estate listing has been created at &a[SignCoordinates]&b. The list price is &a[ListedPricefromSign]&b.

Format for price: $1,000,000.00

And for subclaims:

/broadcast &f[&6RealEstate&f] &bManagement permissions are for sale at &a[SignCoordinates]&b. The Subclaim price is &a[ListedPricefromSign]&b.

Format for price: $1,000,000.00

Optional questions:

**Is your feature request related to a problem? Please describe.**
Connecting buyers and sellers helps establish a market. Advertising real estate sales will help connect sellers with buyers.

**Describe alternatives you've considered**
Another option is updating dynmap-GriefPrevention to change the color of a claim on dynmap when it is for sale.

**Comment by NullCase** [comment]
These broadcasts should also help eliminate confusion over who owns a subclaim.

**Comment by NullCase** [comment]
@RoboMWM I don't know if you will mind, but I sent the first half payment for this, well it seems like a "messaging update" to GPR.

Sent $ right away because issue #7 looks completed now and pay seems well earned. That issue took a bit longer, and I wanted to pay you for it right away.

**Comment by RoboMWM** [comment]
Wow, if-else medley for this one. There are at least 4 separate places where the code ends up listing a claim for sale (i.e. a lot of copy-pasted code).

**Comment by NullCase** [comment]
It sounds like the original implementation has some room for improvement. 

re: commits: Will test them out now. Thanks

**Comment by NullCase** [comment]
Well this seems interesting. There's no broadcast yet. There's no console complaining either. I don't have any more information.

Using this version: https://ci.appveyor.com/project/RoboMWM39862/gprealestate/builds/31566066/artifacts

**Comment by NullCase** [comment]
> Well this seems interesting. There's no broadcast yet. There's no console complaining either. I don't have any more information.
> 
> Using this version: https://ci.appveyor.com/project/RoboMWM39862/gprealestate/builds/31566066/artifacts

to expand on this: I placed a sign, made a real estate offer. The claim went on sale, but no broadcast or console messages.

**Comment by NullCase** [comment]
This annoying thing has just happened. Basically it looks like Paypal is going to stop payments until I satisfy gov. regulations for KYC/AML like a good slave.

It seems straight forward to fix, but ill have to visit the bank this week. Just in case I wanted you to know right away. I'll try to get it fixed asap so I can pay you when this is complete.

![annoying](https://user-images.githubusercontent.com/32785664/77041049-8d4b8d00-698f-11ea-8cb2-a05ac8500077.png)

**Comment by NullCase** [comment]
![bureaucracy](https://user-images.githubusercontent.com/32785664/77049589-baec0280-699e-11ea-9411-fb780617e197.png)

**Comment by RoboMWM** [comment]
Output of /version GPRealEstate ?

**Comment by RoboMWM** [comment]
Oh I see, I create the event but don't fire it. Will fix.

**Comment by RoboMWM** [comment]
Ok, try now

**Comment by NullCase** [comment]
It looks solved @RoboMWM. Very nice. Now to get you paid...

I don't know how long this regulatory issue will take, because of course it says "2-3" business days but... What if I write you by Monday (at the latest).

In case it's solved earlier, I'll keep watch.

**Comment by NullCase** [comment]
It looks like I was able to send $ anyways. I don't know????

Great work @RoboMWM
